networks:
  app:
    external: true
    name: iwindplus-app
services:
  iwindplus-auth:
    build:
      context: iwindplus-auth
      dockerfile: Dockerfile
      args:
        JAR_FILE: "*.jar"
    image: iwindplus-auth:latest
    hostname: iwindplus-auth
    container_name: iwindplus-auth
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - PROFILE_ACTIVE=sit
      - NACOS_SERVER_ADDR=127.0.0.1:8848
      - NACOS_NAMESPACE=iwindplus-sit
      - NACOS_GROUP=IWINDPLUS_GROUP
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=zjLGJX2gRNRT
      - NACOS_WATCH_ENABLED=true
      - NACOS_CLUSTER=iwindplus-sit
      - NACOS_CONFIG_ENABLED=true
      - APP_VESION=v1
      - JAVA_OPTS=-Xmx256m -Xms256m -Xmn96m -XX:+UseStringDeduplication -XX:+TieredCompilation -XX:+UseZGC -XX:ZCollectionInterval=30 -XX:ZAllocationSpikeTolerance=5 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=logs/errorDump.hprof
    expose:
      - "9002"
    networks:
      - app
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./iwindplus-auth/logs:/home/logs
