input {
    tcp {
        # 模式选择为server
        mode => "server"
        host => "0.0.0.0"
        # 这里的端口号要和logback-spring.xml里面的destination匹配
        port => 4560
        # 设定type以区分每个输入源
        codec => json_lines
    }
}

output {
    elasticsearch {
        hosts => "elasticsearch:9200"
        index => "%{env}-%{app}-%{+YYYY.MM.dd}"
        #user => "elastic"
        #password => "zaq12wsx"
    }
}