receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 1s

connectors:
  spanmetrics:

exporters:
  # 1. 链路 → Jaeger
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  # 2. 指标 → Prometheus（remote-write）
  prometheus:
    endpoint: "0.0.0.0:8889"
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter,batch ]
      exporters: [ otlp, spanmetrics ]
    metrics:
      receivers: [ otlp, spanmetrics ]
      processors: [ memory_limiter,batch ]
      exporters: [ prometheus ]