systemLog:
  destination: file
  logAppend: true
  path: /data/log/mongo-27017.log
storage:
  dbPath: /data/db
  journal:
    enabled: true
    commitIntervalMs: 100
  directoryPerDB: true
  syncPeriodSecs: 60
  engine: wiredTiger
  wiredTiger:
    engineConfig:
      cacheSizeGB: 2
      journalCompressor: snappy
      directoryForIndexes: true
    collectionConfig:
      blockCompressor: snappy
    indexConfig:
      prefixCompression: true
processManagement:
  fork: true
  pidFilePath: /data/pid/mongod.pid
net:
  port: 27017
  bindIp:  0.0.0.0
  maxIncomingConnections: 5000
replication:
   oplogSizeMB: 1024
   replSetName: eqxtest3
sharding:
   clusterRole: shardsvr
   archiveMovedChunks: false
   autoSplit: true
   chunkSize: 64M