global:
  resolve_timeout: 5m #处理超时时间，默认为5min
  smtp_smarthost: 'smtp.163.com:465' # 邮箱smtp服务器代理
  smtp_from: 'zengdeguiu88@163.com' # 发送邮箱名称
  smtp_auth_username: 'zengdeguiu88@163.com' # 邮箱名称
  smtp_auth_password: 'ewreBFG7L6Munvm6L3' # 邮箱密码或授权码
# 定义模板信息
templates:
  - '/data/prometheus/alertmanager/template/*.html'
# 定义路由树信息
route:
  group_by: ['alertname'] # 报警分组依据
  group_wait: 10s # 最初即第一次等待多久时间发送一组警报的通知
  group_interval: 10s # 在发送新警报前的等待时间
  repeat_interval: 1h # 发送重复警报的周期
  receiver: 'sytem-os-error' # 发送警报的接收者的名称，以下receivers name的名称
# 定义警报接收者信息
receivers:
  - name: 'sytem-os-error' # 操作系统错误接收者
  email_configs: # 邮箱配置
    - to: 'fanssloop@163.com'  # 接收警报的email配置
  html: '{{ template "system-os-error.html" . }}' # 设定邮箱的内容模板
  headers: { Subject: "[ERROR] 操作系统异常报警"} # 接收邮件的标题
# 抑制规则
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']