# ========================
# 基础配置
# ========================
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0

# ========================
# 关键配置（必须改）
# ========================
# 改成你的宿主机IP（非常重要）
brokerIP1=rmqbroker
listenPort=10911

# ========================
# 存储路径
# ========================
storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog

# ========================
# 自动创建Topic（开发建议开启）
# ========================
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true

# ========================
# ACL核心配置
# ========================
aclEnable=false
aclFile=/home/rocketmq/conf/plain_acl.yml